import Head from 'next/head'
import Link from 'next/link'
import Layout from '../components/Layout.js'

export default function Home() {
  return (
    <Layout>
      <Head>
        <title>Création Numérique</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <p class="text-center font-extrabold text-3xl md:text-5xl">
						Mineur Création du Numérique 🚀
					</p>

				
      <br/>
     <p class="text-center">
      Connectez vous, organisez vos projets, constituez votre équipe
     </p>
    </Layout>
  )
}
